# Site settings
title: Nida Ismail Shah
email: nidaismailshah@gmail.com
description: "Some lines , a bit elaborated"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: nidaismailshah
github_username:  nidaismailshah

# Build settings
markdown: kramdown
permalink: pretty
